### ISSUE TITLE
where to get age_net.caffemodel?

### ISSUE THREAD

**Issue by m3m3-chan** [habom2310/People-tracking-with-Age-and-Gender-detection#1]
Hi,
 thanks for your work!
I tried running the file but I got the following: 
`: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open i "age_gender_models/age_net.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile'`
I understand that the age_net.cafeemodel is missingso where can I get it ?

Thanks,

**Comment by listofbanned** [comment]
Age net: https://drive.google.com/file/d/1kiusFljZc9QfcIYdU2s7xrtWHTraHwmW/view
Gender net: https://drive.google.com/file/d/1W_moLzMlGiELyPxWiYQJ9KFaXroQ_NFQ/view
**Source: https://talhassner.github.io/home/publication/2015_CVPR**

You need to put it inside `age_gender_models` folder.

**Comment by m3m3-chan** [comment]
many thanks!
